### ISSUE TITLE
No ACL found for cluster using io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer

### ISSUE THREAD

**Issue by sookeke** [strimzi/strimzi-kafka-oauth#181]
Hello,

We are currently using keycloak SSO to manage our Kafka ACLs. Everything thing seems to work fine but I want to read and see current resource ACls like topic etc outside of keycloak to be used in our Kafka UI via the Kafka admin client or rest proxy.
So,  I am wondering how exactly this class library(i.e io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer) works.  
For example when I  ran ./kafka-acls.sh --bootstrap-server XXX --command-config XXXX it returns nothing (no ack found in the cluster). When I tried to add ACL to a topic like ./kafka-acls.sh --bootstrap-server XXXX:9092 --command-config XXX \
--add --allow-principal User:XXX \
--producer --topic XXXX
and followed by Get ACL list like  ./kafka-acls.sh --list again, this time the ACL result will be returned but after some time the ACL will disappear. Can someone explain what's going on using this authorizer class library? I was thinking the ACL is stored/cached in the broker.

Thank you

**Comment by sookeke** [comment]
@scholzj  Do you have any answer to this?

**Comment by scholzj** [comment]
I think you would need to explain a bit more about your environment and what exactly are you trying to achieve.

**Comment by scholzj** [comment]
Basically, the Keycloak authorizer does not manage the Kafka ACLs. It has its own authorizer and stores the rules in Keycloak instead of in Kafka. It does not store the ACLs in Kafka as Kafka's ACLs. So you will not see them using the Kafka tools and you cannot manage them with the Kafka tools.

You can use the option `strimzi.authorization.delegate.to.kafka.acl` to delegate the ACLs to the Kafka ACLs as a second layer. But it is not really clear if this is something you use (or want to use) intentionally. But this will still not list the Keycloak rules in Kafka ACLs.

Without knowing more about your environment and intentions, it is hard to understand what is happening and why. For example, if you use the Strimzi User Operator, that would deleet any manually created ACL rules in Kafka.
