### ISSUE TITLE
invalid_token errors 

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-oauth#41]
I have a kafka producer that stands up every morning ( connects to keycloak and then starts to produce data). It's a EKS system. Once a week, a producer fails the authentication with "invalid_token" and then just sits there idle. 

1. Is there a way to detect that the authentication didn't occur and then fail the liveness check?
2. Why might that invalid token occur after the producer had successfully come up and down for a week(pod restart on a cron job)?   
 
`"2020-03-19 07:10:24.378  INFO 11 --- [ad | producer-1] o.apache.kafka.common.network.Selector   : [Producer clientId=producer-1] Failed authentication with kafka-cluster-kafka-8.kafka-cluster-kafka-brokers.mdic-strimzi-pro.svc.cluster.local/100.80.53.16 ({""status"":""invalid_token""})`

**Comment by mstruk** [comment]
If I understand correctly a fresh pod with a producer is started every morning, and once a week it fails immediately after starting up.

Can you share your producer configuration? I'm specifically interested what authentication configuration you use: clientId + clientSecret or refreshToken or accessToken?

Also, can you configure your broker's logging so that io.strimzi logger has DEBUG level, and share your Kafka broker log - that may give more information about the underlying reason for the token being invalid.

**Comment by jrivers96** [comment]
Sorry that I haven't collected the DEBUG logs yet. 

I think I figured a little more information though. I kept restarting the application that was trying to connect to the broker and kept receiving an "invalid_token". The app was trying to connect to a specific broker. When I rolled all the brokers, the application was able to connect properly. 

It seems like the broker might have had an expired key and did not refresh properly? I'll try to collect more information with the DEBUG log if it occurs again. 

```      external:
        type: loadbalancer
        tls: true
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: https://keycloak.dev.us-east-1/auth/realms/pro-realm/protocol/openid-connect/certs
          validIssuerUri: https://keycloak.dev.us-east-1/auth/realms/pro-realm
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt```

**Comment by gitOlf** [comment]
We hope that we can provide some debug information soon, but we face a similar problem. If the keycloak is not available for some time the clients cannot connect to the brokers anymore because the token is invalid. Even if the keycloak auth provider is back online and everything works fine for the other services the tokens are still invalid. We have to restart all brokers to solve the problem. If the keycloak is available without interruption everything is working as it should.

**Comment by mstruk** [comment]
@gitOlf If the problem is on the broker side (which it sounds like since you say you have to restarts the brokers to get it working again) - if you're using `jwksEndpointUri` and see the error logs about missing validation keys, then you can try add the following to your `authentication` section:

    jwksExpirySeconds: 960
    jwksRefreshSeconds: 300

As shown [here](https://github.com/strimzi/strimzi-kafka-operator/issues/2738#issuecomment-607164333).

For more explanation and rationale behind it see [here](https://github.com/strimzi/strimzi-kafka-operator/issues/2738#issuecomment-606587755).

This probably happens because of Keycloak server restarts, and you're probably using a non-persistent pod (regular `deployment` rather than a `statefulset`. In this case every restart of Keycloak will result in new token signing keys, rendering all existing access tokens invalid when Kafka broker reloads the keys from `jwksEndpointUri`. Kafka clients cache the access token, and reuse it for establishing new connection to Kafka broker.
Maybe re-authentication with Keycloak should be performed (and maybe it isn't) by client when it fails to authenticate to Kafka broker with the cached access token.

**Comment by gitOlf** [comment]
@mstruk Thank you for your quick and good response. My current settings are:
`jwksExpirySeconds: 360
 jwksRefreshSeconds: 300`

Everything runs inside an AKS.

I think the problem in this case is not the client. It should be the broker, the restarted the client pods many times (after the keycloak pods are back online). The clients cannot find the topics and have messages about invalid tokens. The problem is only solved by killing the kafka broker pods. 

We use the Keycloak Helm Chart: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak 

I do not saw any message of:
`java.lang.RuntimeException: Failed to fetch public keys needed to validate JWT signatures ...` or anything likely, only token_invalid error messages. 

The Image Version is: `strimzi/kafka:0.16.2-kafka-2.4.0 (We plan  a update in the next days to 0.17.0-kafka-2.4.0)`.

I found also another behavior: If the client is connected to the broker and I lock out the client by resetting its secret in keycloak, the connection is still active and stays active (even after the lifespan of the token). I think the authentication/authorization is only made when the connection is established?

**Comment by mstruk** [comment]
@gitOlf The behaviour you describe is consistent with Kafka Brokers still using the cached JWKS keys which have been rotated on Keycloak at restart (if Keycloak configuration is not persistent). Kafka Brokers will reload JWKS keys after the configured jwksRefreshSeconds. When this happens the Kafka clients should again be able to successfully authenticate.

You are correct that authentication is only made when the connection is established - that's how Kafka authentication works. If broker is to understand the token expiry also as the session expiry, you would periodically see as a client an error which you would have to handle by starting a completely new session. Currently there is no way to forcefully drop the connections whose tokens have expired or been made inactive. Using an expired or inactive token to authenticate a new Kafka client session will not work though.

Another way to revoke access that you can try is to use authorization. Authorization checks are performed for every operation the client performs, thus revoking access using authorization rules should have immediate effect, but it would not take the access token into account - you'd have to manually change ACL for the user. It would require a special authorizer to also check if access token is still valid.

The whole business of expiring the session with the expiry of the access token makes things quite more complex. We may add some solution for this in the future.

**Comment by gitOlf** [comment]
@mstruk Thank you again, one last question. We looked at your implementation at https://github.com/strimzi/strimzi-kafka-oauth/blob/master/oauth-common/src/main/java/io/strimzi/kafka/oauth/validator/JWTSignatureValidator.java . 

In the constructor scheduler.scheduleAtFixedRate with fetchKeys() is called. fetchKeys throws a runtime exception as soon as any exception occurs. This ends the periodic execution of the scheduler, doesn't it? 

`(java.util.concurrent.ScheduledThreadPoolExecutor#scheduleAtFixedRate)
 * <li>An execution of the task throws an exception.  In this case
 * calling {@link Future#get() get} on the returned future will throw
 * {@link ExecutionException}, holding the exception as its cause.
 * </ul>
 * Subsequent executions are suppressed
`

**Comment by mstruk** [comment]
@gitOlf Indeed, this looks like a bug. That's a nice catch!

And we need to add a test for this ...

**Comment by jrivers96** [comment]
The above problem description was our problem too. We have PVM turned on for keycloak, but still the token gets invalidated somehow when a keycloak restarts. We haven't tried going to 0.17 yet.
